# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-18 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180818_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='emergency_contact',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='id_num',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='身份证'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='sex',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentapply',
            unique_together=set([('customer', 'class_grade')]),
        ),
    ]
