# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-18 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180818_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='emergency_contact',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='紧急联系人'),
        ),
    ]
