# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-21 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180818_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplate',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentapply',
            name='contract_agreed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='合同签订时间'),
        ),
        migrations.AlterField(
            model_name='studentapply',
            name='contract_approved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='合同审核时间'),
        ),
    ]
