# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-22 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180821_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapply',
            name='contract_agreed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='合同同意时间'),
        ),
    ]
